"""Build glossary.yml from layered Markdown glossary files.

Input files, in priority order:
    novels/<slug>/glossary/locked.md     -> lock=locked, priority=1
    novels/<slug>/glossary/reference.md  -> lock=reference, priority=2
    novels/<slug>/glossary/auto.md       -> lock=auto, priority=3

Output:
    novels/<slug>/glossary/glossary.yml

The generated YAML is consumed by tools/glossary.py. Edit the Markdown source
files, then run this script to regenerate the YAML snapshot.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
NOVELS_DIR = PROJECT_ROOT / "novels"

LAYERS = [
    ("locked.md", "locked", 1),
    ("reference.md", "reference", 2),
    ("auto.md", "auto", 3),
]


def _split_table_row(line: str) -> List[str]:
    """Split a Markdown table row into trimmed cells."""
    stripped = line.strip()
    if not stripped.startswith("|") or not stripped.endswith("|"):
        return []
    return [cell.strip() for cell in stripped.strip("|").split("|")]


def _looks_like_separator(cells: List[str]) -> bool:
    return bool(cells) and all(set(cell.replace(":", "").strip()) <= {"-"} for cell in cells)


def _looks_like_header(cells: List[str]) -> bool:
    lowered = [cell.lower() for cell in cells]
    return "source" in lowered and "thai" in lowered


def _parse_priority_and_notes(extra_cells: List[str], default_priority: int) -> tuple[int, str]:
    priority = default_priority
    notes_cells = list(extra_cells)

    if notes_cells:
        first = notes_cells[0].strip()
        if first.isdigit():
            priority = int(first)
            notes_cells = notes_cells[1:]

    return priority, " | ".join(cell for cell in notes_cells if cell).strip()


def parse_markdown_terms(path: Path, lock: str, default_priority: int) -> List[Dict[str, object]]:
    """Parse glossary terms from Markdown table rows.

    The existing glossary Markdown files are not perfectly uniform. This parser
    accepts both of these shapes:
        | Source | Thai | Category | Notes |
        | Source | Thai | Category | Priority | Notes |
        | Source | Thai | Category | Priority | Lock | Notes |
    """
    if not path.exists():
        return []

    terms: List[Dict[str, object]] = []
    seen_sources: set[str] = set()

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        cells = _split_table_row(raw_line)
        if not cells or _looks_like_separator(cells) or _looks_like_header(cells):
            continue
        if len(cells) < 3:
            continue

        source = cells[0].strip()
        thai = cells[1].strip()
        category = cells[2].strip() or "ทั่วไป"
        if not source or not thai or source in seen_sources:
            continue

        extra = cells[3:]
        priority, notes = _parse_priority_and_notes(extra, default_priority)

        explicit_lock = lock
        if len(extra) >= 2 and extra[1].strip() in {"locked", "reference", "auto"}:
            explicit_lock = extra[1].strip()
            notes = " | ".join(extra[2:]).strip()

        terms.append(
            {
                "source": source,
                "thai": thai,
                "category": category,
                "priority": priority,
                "lock": explicit_lock,
                "explanation": "",
                "notes": notes,
            }
        )
        seen_sources.add(source)

    return terms


def build_terms(slug: str) -> List[Dict[str, object]]:
    glossary_dir = NOVELS_DIR / slug / "glossary"
    all_terms: List[Dict[str, object]] = []
    seen_sources: set[str] = set()

    for filename, lock, default_priority in LAYERS:
        for term in parse_markdown_terms(glossary_dir / filename, lock, default_priority):
            source = str(term["source"])
            if source in seen_sources:
                continue
            all_terms.append(term)
            seen_sources.add(source)

    all_terms.sort(key=lambda item: (int(item.get("priority", 3)), str(item.get("source", ""))))
    return all_terms


def write_yaml(slug: str, terms: Iterable[Dict[str, object]]) -> Path:
    glossary_dir = NOVELS_DIR / slug / "glossary"
    out_path = glossary_dir / "glossary.yml"
    terms_list = list(terms)

    header = (
        "# Auto-generated by tools/build_yaml.py — DO NOT EDIT BY HAND\n"
        f"# Source: novels/{slug}/glossary/{{locked,reference,auto}}.md\n"
        "# Edit .md, then run `python tools/build_yaml.py --novel " + slug + "` to regenerate.\n"
        f"# Terms: {len(terms_list)}\n\n"
    )
    payload = yaml.safe_dump(
        {"terms": terms_list},
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
    )
    out_path.write_text(header + payload, encoding="utf-8")
    return out_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Build glossary.yml from layered Markdown glossary files.")
    parser.add_argument("--novel", default="global-descent", help="Novel slug under novels/.")
    args = parser.parse_args()

    novel_root = NOVELS_DIR / args.novel
    if not novel_root.exists():
        raise SystemExit(f"Novel not found: {novel_root}")

    terms = build_terms(args.novel)
    out_path = write_yaml(args.novel, terms)
    print(f"Built {out_path} with {len(terms)} terms")


if __name__ == "__main__":
    main()
